name: fluent_lyrics
description: "Fluent Lyrics, a lyrics viewer supports various sources."

version: 0.0.11

publish_to: 'none'

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  scrollable_positioned_list: ^0.3.8
  provider: ^6.1.5+1
  http: ^1.6.0
  shared_preferences: ^2.5.1
  dbus: ^0.7.11
  crypto: ^3.0.7
  encrypt: ^5.0.3
  async: ^2.13.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  package_info_plus: ^8.1.2
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/album_art.png

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/google/Outfit/VariableFont_wght.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
  min_sdk_android: 28
